### PR TITLE
feat: make methods in `ManeTranscript` public

### LINKED ISSUE #229: Mark `MANETranscript._validate_index()` and `MANETranscript._get_reading_frame()` as public
They're called directly in Variation Normalizer, so we may want to designate it as public (i.e. drop the leading underscore in the name, and fill in the docstring more) in a future release.

### PR DESCRIPTION
**Pull request by korikuzma**
close #229

* `ManeTranscript._validate_index` -> `ManeTranscript.validate_index`
* `ManeTranscript._get_reading_frame` -> `ManeTranscript.get_reading_frame`

### CODE REVIEW

**Comment by jsstevenson** [comment]
👍 up to you if you want to do this here or save it for a more consequential case, but we can also keep the old methods for a time, have them re-direct to the newly-named methods, and use the [warnings module](https://docs.python.org/3/library/warnings.html) to issue deprecation warnings until they're changed

technically, I also think you could argue this isn't a breaking change (because the previous thing was private and therefore not *supposed* to be accessed) but since Variation Normalizer was calling the private methods it'll still break compatbility. could go either way imo

**Review by jsstevenson — APPROVED** [review]

**Comment by korikuzma** [comment]
@jsstevenson 

> 👍 up to you if you want to do this here or save it for a more consequential case, but we can also keep the old methods for a time, have them re-direct to the newly-named methods, and use the [warnings module](https://docs.python.org/3/library/warnings.html) to issue deprecation warnings until they're changed

I'm pretty sure we're the only ones using Cool-Seq-Tool atm. I think this would be good to do in the future once we've made a major release. But if you think it's important to do now, I can.

> technically, I also think you could argue this isn't a breaking change (because the previous thing was private and therefore not supposed to be accessed) but since Variation Normalizer was calling the private methods it'll still break compatbility. could go either way imo

I always go back and forth on these. I think this is a case where it would be nice to have documentation for our lab to decide what to do. I can update the title to have it not be a breaking change.

**Comment by jsstevenson** [comment]
yeah fine either way imo

**Comment by korikuzma** [comment]
@jsstevenson Okay, I'll just keep it as is.

**Pull request merged**
