### PR TITLE
fix: include package data

### LINKED ISSUE #256: Add package data
The `0.4.0.dev0` release does not include required package data (`transcript_mappings.tsv`)

### PR DESCRIPTION
**Pull request by korikuzma**
close #256 . Followed https://setuptools.pypa.io/en/latest/userguide/datafiles.html#subdirectory-for-data-files

Notes:
* Includes transcript_mappings.tsv

### CODE REVIEW

**Review by jsstevenson — APPROVED** [review]

**Comment by jsstevenson** [comment]
I'm ok with pushing that failed docs build to a separate issue if you want to get this out now

**Comment by korikuzma** [comment]
@jsstevenson tbh, I do not know how the docs work

**Comment by jsstevenson** [comment]
@korikuzma same!

**Comment by korikuzma** [comment]
python3 -m pip install -i https://test.pypi.org/simple/ cool-seq-tool --no-deps

**Pull request merged**
