### PR TITLE
refactor: update to lastest version of gene-normalizer

### LINKED ISSUE #145: Update gene-normalizer
In 0.2.9 and 0.1.34, gene-normalizer's `QueryHandler` class now takes a `Database` as a param rather than `db_url` and `db_region`

### PR DESCRIPTION
**Pull request by korikuzma**
close #145 

Needed for work in [this](https://github.com/cancervariants/variation-normalization/issues/394) variation normalizer issue 
- QueryHandler now accepts Database instance in the latest version
- CoolSeqTool now has a gene_query_handler instance var

### CODE REVIEW

**Review by jsstevenson — CHANGES_REQUESTED** [review]
We'll need to update gene-norm dependencies to be 0.1.34+/0.2.9+ since that was a breaking change

**Comment by korikuzma** [comment]
> We'll need to update gene-norm dependencies to be 0.1.34+/0.2.9+ since that was a breaking change

@jsstevenson I'm not sure what the notation is for allowing multiple minor versions, while also excluding some older versions. I'm looking at [this](https://peps.python.org/pep-0440/#version-specifiers).

**Comment by jsstevenson** [comment]
@korikuzma yeah that's a good point. Pinning 0.1.29+ at least solves half of the problem (sort of joking, but sort of serious)

**Comment by jsstevenson** [comment]
@korikuzma Fine w/ me

**Review by jsstevenson — APPROVED** [review]

**Pull request merged**
